name: Xbox Allies
favicon: null
layout_spectrum: 0.07845436315983534
typography_spectrum: 0.5117257514502853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6585914080496877
  lightness: 0.4589779772795737
  saturation: 0.9262977961916476
  rhythmicContrast: 0.12993834004737437
purpose: []
