name: Xbox Allies
favicon: null
layout_spectrum: 0.97914
typography_spectrum: 0.32554
title: Xbox Allies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#67a24b'
    - '#e2e3de'
    - '#447132'
    - '#41413a'
  brandStrength: 0.6585914080496877
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
